In [2]:
import numpy as np

def calculate_mean_along_axis0(array):
    # Calculate the mean along axis 0
    mean_axis0 = np.mean(array, axis=0)
    return mean_axis0

# Create a sample NumPy array
sample_array = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

# Calculate the mean along axis 0
result = calculate_mean_along_axis0(sample_array)

print("Mean along axis 0:", result)
sample_array.mean(axis=0)

Mean along axis 0: [4. 5. 6.]


array([4., 5., 6.])

In [3]:
import pandas as pd

def calculate_mean_along_axis0(dataframe):
    # Calculate the mean along axis 0
    mean_axis0 = dataframe.mean(axis=0)
    return mean_axis0

# Create a sample pandas DataFrame
data = {'Column1': [1, 4, 7],
        'Column2': [2, 5, 8],
        'Column3': [3, 6, 9]}
sample_dataframe = pd.DataFrame(data)

# Calculate the mean along axis 0
result = calculate_mean_along_axis0(sample_dataframe)

print("Mean along axis 0:\n", result)


Mean along axis 0:
 Column1    4.0
Column2    5.0
Column3    6.0
dtype: float64


In [7]:
sample_dataframe.mean(axis=1)

0    2.0
1    5.0
2    8.0
dtype: float64

In [6]:
sample_dataframe

Column1  Column2  Column3
0        1        2        3
1        4        5        6
2        7        8        9

In [8]:
print('hi')

hi


In [9]:
from tensorflow.keras.layers import TextVectorization


In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define parameters
max_tokens = 10  # Vocabulary size
sequence_length = 5  # Length of input sequences

# Create a sample input sequence
input_sequence = [2, 4, 1, 7, 3]

# Define the Input Layer
inputs = keras.Input(shape=(sequence_length,), dtype="int64")

# Perform one-hot encoding
embedded = tf.one_hot(inputs, depth=max_tokens)

# Create a model with the embedding layer
model = keras.Model(inputs, embedded)

# Display the one-hot encoded sequence
one_hot_encoded_sequence = model.predict([input_sequence])
print("One-Hot Encoded Sequence:")
print(one_hot_encoded_sequence)


1/1 [==============================] - 1s 1s/step
One-Hot Encoded Sequence:
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]]


In [3]:
input_sequence = [2, 4,0, 7, 3]

one_hot_encoded_sequence = model.predict([input_sequence])
print("One-Hot Encoded Sequence:")
print(one_hot_encoded_sequence)

1/1 [==============================] - 0s 410ms/step
One-Hot Encoded Sequence:
[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]]


In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Embedding

# Define vocabulary size and embedding dimension
vocab_size = 10
embedding_dim = 5

# Create a toy sequence with padding
sequences = np.array([[1, 2, 3, 0], [4, 5, 0, 0], [6, 7, 8, 9]])

# Create an embedding layer with mask_zero=True
embedding_layer = Embedding(
    input_dim=vocab_size,
    output_dim=embedding_dim,
    mask_zero=True  # Mask padding tokens
)

# Apply the embedding layer to the sequences
embedded_sequences = embedding_layer(sequences)

# Print the original sequences and their embeddings
print("Original sequences:\n", sequences)
print("\nEmbedded sequences:\n", embedded_sequences.numpy())


Original sequences:
 [[1 2 3 0]
 [4 5 0 0]
 [6 7 8 9]]

Embedded sequences:
 [[[-3.9190173e-02  4.7549192e-02 -5.6616068e-03  7.8545213e-03
    2.4777722e-02]
  [-4.4728734e-02  3.6977123e-02  3.2341424e-02 -1.1885691e-02
    2.1390606e-02]
  [-2.7083326e-02 -4.4503152e-02  3.4754481e-02 -1.8973947e-03
   -4.7852565e-02]
  [ 3.5931874e-02  3.3987164e-03  3.9700676e-02 -3.8502775e-02
   -4.9115371e-02]]

 [[ 4.7227088e-02 -6.2262192e-03 -1.8088065e-02 -1.5391588e-02
    3.7944805e-02]
  [-1.8180598e-02  2.1653067e-02  3.5450425e-02 -4.7611561e-02
   -2.1008600e-02]
  [ 3.5931874e-02  3.3987164e-03  3.9700676e-02 -3.8502775e-02
   -4.9115371e-02]
  [ 3.5931874e-02  3.3987164e-03  3.9700676e-02 -3.8502775e-02
   -4.9115371e-02]]

 [[ 5.8721192e-03  5.8426149e-03  7.4446201e-05 -1.3410129e-02
    1.6996194e-02]
  [ 1.7509460e-03 -2.1479595e-02 -4.2637810e-03 -1.2347281e-02
    3.7635121e-02]
  [-1.8035747e-02 -3.5052784e-03 -6.8548322e-03  5.6091659e-03
    4.5231555e-02]
  [-2.4215793e-02